### ISSUE TITLE
update the starter kit to support kalliope v0.5.0

### ISSUE THREAD

**Issue by Sispheor** [kalliope-project/kalliope_starter_de#2]
You can [see here the changes](https://github.com/kalliope-project/kalliope_starter_en/commit/5bd4ad5f45b22fab26b6ff54fd578e8436601595) I made on the EN version

**Comment by seppeel** [comment]
I just wanted to do this and realized its already done with #3 
-> This can be closed i think?
BTW: Thanks for your work, my new RPI will arrive today and then i will checkout kalliope :)

greetings
seppel
